- name: Request images list from  API
  uri:
    url: "{{ AUTH_URL_IMAGES }}"
    method: GET
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: imageslist

- debug:
    msg: "{{ imageslist.json }}"

