- name: Request vpc list from AUTH API
  uri:
    url: "{{ AUTH_URL_VPCS }}"
    method: GET
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: vpclist

- debug:
    msg: "{{ vpclist.json }}"

